version: '3.8'

services:
  app:
    build: .
    container_name: bumaview-app
    restart: always
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: bumaview-db
    restart: always
    environment:
      POSTGRES_DB: bumadb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
