spring:
  application:
    name: bumaview

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format-sql: true
          default_batch_fetch_size: 500
      open-in-view: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

token:
  secret: ${TOKEN_SECRET}
  access-token-expiration-time: ${ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-expiration-time: ${REFRESH_TOKEN_EXPIRATION_TIME}
